### ISSUE TITLE
Cant Connect to AWS Region

### ISSUE THREAD

**Issue by ibr123** [smithfarm/ceph-auto-aws#37]
Hi, 

Thanks for sharing this app, I followed the steps of installation until I'm stuck at [Region and Availability Zone](https://github.com/smithfarm/ceph-auto-aws#region-and-availability-zone) I added to the aws.yaml 

```
region:
  availability_zone:
  region_str: us-east-1

```
but instead of getting the message that you have added, I get the following:

```
2018-02-07 14:58:43,511 INFO Loaded yaml tree from './aws.yaml'
2018-02-07 14:58:43,511 INFO Testing connectivity to AWS Region {'region_str': 'us-east-1', 'availability_zone': None}
2018-02-07 14:58:43,613 ERROR 403 Forbidden
2018-02-07 14:58:43,614 ERROR <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>45117326-0397-4fbe-b5a2-21c44d836ede</RequestID></Response>
Traceback (most recent call last):
  File "/home/ubuntu/ceph_app/ceph-auto-aws/virtualenv/bin/ho", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/ceph_app/ceph-auto-aws/bin/ho", line 24, in <module>
    sys.exit(HandsOn().run(sys.argv[1:]))
  File "/home/ubuntu/ceph_app/ceph-auto-aws/handson/main.py", line 195, in run
    self.args.func(self.args).run()
  File "/home/ubuntu/ceph_app/ceph-auto-aws/handson/probe.py", line 318, in run
    vpc_count = len(vpc_conn.get_all_vpcs())
  File "/home/ubuntu/ceph_app/ceph-auto-aws/virtualenv/local/lib/python2.7/site-packages/boto/vpc/__init__.py", line 110, in get_all_vpcs
    return self.get_list('DescribeVpcs', params, [('item', VPC)])
  File "/home/ubuntu/ceph_app/ceph-auto-aws/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>45117326-0397-4fbe-b5a2-21c44d836ede</RequestID></Response>
```
yet, my EC2 instance have all the permission that It can have, I think the error happens [here](https://github.com/smithfarm/ceph-auto-aws/blob/b2bb4422d845ba6a8d28fa47cfc95f1368778849/handson/probe.py#L318)
I also provided the Availability Zone as well, yet same problem, how to solve this problem

Thanks

**Comment by ibr123** [comment]
I though that the Permissions should have been assigned to the EC2 instance, and it turned out that they should be assigned to the user access key and secret key **"at boto"**
